// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD45RXqfsPs-K25zOiCDPsO2EY55UMCIaE',
    appId: '1:13938328535:web:070f08b80b0bafd3370192',
    messagingSenderId: '13938328535',
    projectId: 'courseappproject',
    authDomain: 'courseappproject.firebaseapp.com',
    storageBucket: 'courseappproject.firebasestorage.app',
    measurementId: 'G-817M3ZC9TZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDFmYBnHs-wgS9uhZB5NVetDQB2MmXwYME',
    appId: '1:13938328535:android:5353155743c4b2f3370192',
    messagingSenderId: '13938328535',
    projectId: 'courseappproject',
    storageBucket: 'courseappproject.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA1P8VQ8RD0x3omHjG34V42eSsRtHd1Qqc',
    appId: '1:13938328535:ios:b68d73072656c6ef370192',
    messagingSenderId: '13938328535',
    projectId: 'courseappproject',
    storageBucket: 'courseappproject.firebasestorage.app',
    iosBundleId: 'com.example.courseapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA1P8VQ8RD0x3omHjG34V42eSsRtHd1Qqc',
    appId: '1:13938328535:ios:b68d73072656c6ef370192',
    messagingSenderId: '13938328535',
    projectId: 'courseappproject',
    storageBucket: 'courseappproject.firebasestorage.app',
    iosBundleId: 'com.example.courseapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD45RXqfsPs-K25zOiCDPsO2EY55UMCIaE',
    appId: '1:13938328535:web:ce377f7a8bbce371370192',
    messagingSenderId: '13938328535',
    projectId: 'courseappproject',
    authDomain: 'courseappproject.firebaseapp.com',
    storageBucket: 'courseappproject.firebasestorage.app',
    measurementId: 'G-DMDRJQ20G6',
  );
}
